### ISSUE TITLE
No Skeletonization for a Cube

### ISSUE THREAD

**Issue by Foxelmanian** [phi-max/skeleton3d-matlab#4]
# No Skeletonization for a Cube
## 1. Input: Cube  of 4x4x4, 6x6x6, 8x8x8 ....
The cube was voxelized and padded with 1 empty voxel around them.

## 2. Experiment
Applying the Voxel Model to the skeletonization algorithm. 
### Current algorithm:
Checks only the simple point condition (connectivity) during the sequential check.

### Suggestion:
Check the euler characeristic during the sequential check aswell.

**Comment by phi-max** [comment]
Thank you!
