### ISSUE TITLE
I cannot find the Skel2Graph3D package

### ISSUE THREAD

**Issue by debinz** [phi-max/skeleton3d-matlab#6]
Hi!

I am using your great code, but I cannot find the Skel2Graph3D package since I want to prune secondary mid-surface branches. Can you give me some advice about that? Thank you for your kind assistance!

Zeng

**Comment by phi-max** [comment]
Hello,
it is also in my github repository (https://github.com/phi-max/skel2graph3d-matlab) or on the MATLAB file exchange.
