### ISSUE TITLE
.obj files to graphs

### ISSUE THREAD

**Issue by meghalD** [phi-max/skeleton3d-matlab#7]
Hello,
I was wanting to convert the .obj files for 3D models to skeleton and convert those into graphs further. For skeletonization I found out that skeleton-3D works great. But I don't know can it accept .obj format as input. If not, what should be the format for skeletonization and further graph generation using skel2graph.

**Comment by phi-max** [comment]
this package applies voxel-based thinning, and requires voxel (raster) images. To use .obj files (meshes), you would have to convert the meshes to binary volumes - there are probably tools that can do that.
